FROM node:18.12.1-slim as build-stage

ARG LOCAL_DIR=.

WORKDIR /app

COPY $LOCAL_DIR/package*.json /app/
RUN npm install
COPY ./$LOCAL_DIR/public/ /app/public
COPY ./$LOCAL_DIR/src/ /app/src
RUN npm run build

FROM nginx:1.23.3-alpine-slim

ARG LOCAL_DIR=.

COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY ./$LOCAL_DIR/currency-converter.conf.template /etc/nginx/conf.d/
COPY ./$LOCAL_DIR/start_nginx.sh /
