version: '3.8'
services:
  redis:
      container_name: redis
      restart: always
      image: redis:7.0.4
      volumes:
        - redis-vol:/data
      ports:
        - "${REDIS__PORT}:${REDIS__PORT}"
  currency_api:
    environment:
      - MYSQL__HOST=mysqldb
      - API__STARTUP__UVICORN_RELOAD=False
      - REDIS__HOST=redis
    container_name: currency_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    entrypoint: python api_main.py
    depends_on:
      - currency_updater
      - mysqldb
    ports:
      - "${API__STARTUP__PORT}:${API__STARTUP__PORT}"
  currency_updater:
    environment:
      - MYSQL__HOST=mysqldb
    container_name: currency_updater
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.db
    entrypoint: python start_updates.py
    depends_on:
      - mysqldb

  react_frontend:
    environment:
      - PORT="${REACT__HOST_PORT}"
    container_name: react_frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    entrypoint: npm start --port=${REACT__HOST_PORT}
    depends_on:
      - currency_api
      - mysqldb
    ports:
      - "${REACT__HOST_PORT}:${REACT__HOST_PORT}"
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL__ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL__USER}'
      MYSQL_PASSWORD: '${MYSQL__PASSWORD}'
      MYSQL_DATABASE: '${MYSQL__DATABASE}'
    volumes:
      - vol:/var/lib/mysql
    ports:
      - "${MYSQL__PORT}:3306"
volumes:
  vol:
  redis-vol:
