apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-dev-server
  labels:
    name: react-dev-server
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      app: react-app
  template:
    metadata:
      labels:
        type: frontend
        app: react-app
    spec:
      containers:
        - name: react-dev-server
          command: ["npm", "start"]
          image: currency-converter-dev-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
          - name: PORT
            value: '3002'
          - name: REACT_APP_PROXY_HOST
            value: 'http://api-server-svc:8080'

---

apiVersion: v1
kind: Service
metadata:
  name: react-dev-server-svc
  labels:
    service: react-dev-server-svc
spec:
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: react-app
