apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: redis-app
  template:
    metadata:
      labels:
        type: backend
        app: redis-app
    spec:
      containers:
        - name: redis
          image: redis:7.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-server-svc
  labels:
    service: redis-server-svc
spec:
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-app
